# Site settings
title: Huntly Cameron
email: huntly.cameron@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer, drummer, bread maker and pet hoomin to Onion 😺
baseurl: "" # the subpath of your site, e.g. /blog/
url: "huntlyc.github.io" # the base hostname & protocol for your site
twitter_username: huntlyc
github_username:  huntlyc

# Build settings
markdown: kramdown
